# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: Eclipse SDV

url: http://127.0.0.1:8000

base_path: /eclipse-sdv-projects-landscape2

colors:
  color1: "rgba(0, 107, 204, 1)"
  color2: "rgba(255, 0, 170, 1)"
  color3: "rgba(96, 149, 214, 1)"
  color4: "rgba(0, 42, 81, 0.7)"
  color5: "rgba(1, 107, 204, 0.7)"
  color6: "rgba(0, 42, 81, 0.7)"
  color7: "rgba(180, 219, 255, 1)"

description: Eclipse SDV

featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Graduated

footer:
  links:
    facebook: "https://www.facebook.com/--"
    flickr: "https://www.flickr.com/people/108559379@N08/"
    github: "https://github.com/enterprises/eclipse-foundation/organizations"
    homepage: "https://sdv.eclipse.org/"
    instagram: "https://www.instagram.com/eclipsesdv/"
    linkedin: "https://www.linkedin.com/company/software-defined-vehicle/"
    slack: "https://join.slack.com/t/sdvworkinggroup/shared_invite/zt-3c5ied1nk-Mk87s4kOX7ipcNo_VktlWg"
    twitter: "https://x.com/SDVeclipse/"
    youtube: "https://www.youtube.com/@EclipseFdn"
  logo: "https://sdv.eclipse.org/images/logo/sdv-logo-color.svg"

grid_items_size: large

groups:
  - name: SDV Projects
    categories:
      - Tooling Devops
      - Distributions and Frameworks
      - RTOS
      - Example Applications
      - Service Fabric and Communication
      - Runtime and Orchestration
      - AI
      - Unmapped

header:
  links:
    github: "https://github.com/enterprises/eclipse-foundation/organizations"
  logo: "https://sdv.eclipse.org/images/logo/sdv-logo-color.svg"

screenshot_width: 1500
